
---
- name: Clear Firefox cache2 directories on Linux for all users
  hosts: CH(MDU)
  become: true
  gather_facts: false

  vars:
    skip_users:
      - root
      - nobody
      - systemd-network
      - _apt

  tasks:

    - name: Get list of all user home directories
      find:
        paths: /home
        file_type: directory
        depth: 1
      register: user_dirs

    - name: Filter valid Linux users
      set_fact:
        valid_users: >-
          {{
            user_dirs.files
            | map(attribute='path')
            | map('basename')
            | reject('in', skip_users)
            | list
          }}

    - name: Find Firefox cache2 folders for all valid users
      find:
        paths: "/home/{{ item }}/.cache/mozilla/firefox"
        patterns: "cache2"
        recurse: true
        file_type: directory
      loop: "{{ valid_users }}"
      register: firefox_cache_folders
      ignore_errors: true

    - name: Delete Firefox 'cache2' folders
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined

    - name: Recreate empty 'cache2' folders
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.path.split('/')[2] }}"
        group: "{{ item.path.split('/')[2] }}"
        mode: '0755'
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined
