---
- name: Deploy Firefox enterprise policies safely
  hosts: ansibletesting
  become: yes
  gather_facts: no

  tasks:

    - name: Get Firefox launcher
      shell: readlink -f "$(which firefox)"
      register: firefox_launcher
      changed_when: false

    - name: Check if corporate launcher is used
      set_fact:
        is_wrapper: "{{ firefox_launcher.stdout == '/etc/firefox/firefox' }}"

    - name: Resolve real Firefox binary from corporate launcher
      shell: strings /etc/firefox/firefox | grep -Eo '/(opt|usr/lib)/firefox/firefox' | head -1
      register: wrapped_firefox
      when: is_wrapper
      changed_when: false

    - name: Set real Firefox binary path
      set_fact:
        real_firefox: "{{ wrapped_firefox.stdout if is_wrapper else firefox_launcher.stdout }}"

    - name: Derive Firefox installation directory
      set_fact:
        firefox_home: "{{ real_firefox | regex_replace('/firefox$', '') }}"

    - name: Show detected Firefox paths
      debug:
        msg:
          - "Firefox launcher: {{ firefox_launcher.stdout }}"
          - "Real Firefox binary: {{ real_firefox }}"
          - "Firefox home: {{ firefox_home }}"

    - name: Ensure distribution directory exists
      file:
        path: "{{ firefox_home }}/distribution"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy Firefox locked enterprise policies
      copy:
        dest: "{{ firefox_home }}/distribution/policies.json"
        mode: '0644'
        content: |
          {
            "policies": {
              "DisableAppUpdate": true,
              "DisablePasswordManager": true,
              "DisableFirefoxAccounts": true,
              "BlockAboutAddons": true,
              "Preferences": {
                "signon.rememberSignons": {
                  "Value": false,
                  "Status": "locked"
                }
              }
            }
          }
