- name: Audit Firefox policy directories
  hosts: Unit-2&3
  become: yes
  gather_facts: no

  tasks:

    - name: Check Firefox
      command: firefox --version
      register: firefox_version
      ignore_errors: yes
      changed_when: false

    - name: Skip if Firefox not installed
      meta: end_host
      when: firefox_version.rc != 0

    - name: Get real Firefox binary
      shell: readlink -f "$(which firefox)"
      register: firefox_real
      changed_when: false

    - name: Set Firefox policy root
      set_fact:
        firefox_policy_root: >-
          {% if firefox_real.stdout == '/usr/bin/firefox' %}
          /usr/lib/firefox
          {% else %}
          {{ firefox_real.stdout | regex_replace('/firefox$', '') }}
          {% endif %}

    - name: Check distribution folder
      stat:
        path: "{{ firefox_policy_root }}/distribution"
      register: dist_dir

    - name: Check policies.json
      stat:
        path: "{{ firefox_policy_root }}/distribution/policies.json"
      register: policy_file

    - name: Show audit result
      debug:
        msg: |
          ===== {{ inventory_hostname }} =====
          Firefox binary: {{ firefox_real.stdout }}
          Policy root: {{ firefox_policy_root }}
          distribution exists: {{ dist_dir.stat.exists }}
          policies.json exists: {{ policy_file.stat.exists }}
