---
- name: Firefox Enterprise Policy Audit
  hosts: Test-Batch1 
  become: yes
  gather_facts: no

  tasks:

    - name: Find firefox binary
      shell: "command -v firefox"
      register: firefox_cmd
      changed_when: false
      failed_when: firefox_cmd.rc != 0

    - name: Resolve real firefox binary path
      shell: "readlink -f {{ firefox_cmd.stdout }}"
      register: firefox_real
      changed_when: false

    - name: Set Firefox install directory
      set_fact:
        firefox_install_dir: "{{ firefox_real.stdout | dirname }}"

    - name: Define policy paths
      set_fact:
        dist_policy: "{{ firefox_install_dir }}/distribution/policies.json"
        etc_policy: "/etc/firefox/policies/policies.json"

    - name: Check distribution policy
      stat:
        path: "{{ dist_policy }}"
      register: dist_policy_stat

    - name: Check /etc policy
      stat:
        path: "{{ etc_policy }}"
      register: etc_policy_stat

    - name: Determine active policy source
      set_fact:
        active_policy_source: >-
          {% if dist_policy_stat.stat.exists %}
            INSTALLATION_DIRECTORY
          {% elif etc_policy_stat.stat.exists %}
            ETC
          {% else %}
            NONE
          {% endif %}
        active_policy_path: >-
          {% if dist_policy_stat.stat.exists %}
            {{ dist_policy }}
          {% elif etc_policy_stat.stat.exists %}
            {{ etc_policy }}
          {% else %}
            NONE
          {% endif %}

    - name: Firefox policy report
      debug:
        msg:
          - "Firefox Binary  : {{ firefox_real.stdout }}"
          - "Install Dir     : {{ firefox_install_dir }}"
          - "Dist Policy     : {{ dist_policy }} (exists={{ dist_policy_stat.stat.exists }})"
          - "ETC Policy      : {{ etc_policy }} (exists={{ etc_policy_stat.stat.exists }})"
          - "ACTIVE SOURCE   : {{ active_policy_source }}"
          - "ACTIVE FILE     : {{ active_policy_path }}"
