---
- name: Collect simplified DHCP info
  hosts: linux_servers
  become: yes
  gather_facts: no

  vars:
    # Filter log lines to include only 'new lease' lines
    dhcp_filter: "state changed new lease"

  tasks:

    - name: Get NetworkManager DHCP logs (last 1 day)
      shell: journalctl -u NetworkManager --since "1 day ago" | grep -i "{{ dhcp_filter }}"
      register: dhcp_logs
      changed_when: false
      failed_when: false

    - name: Parse IP addresses from DHCP logs
      set_fact:
        dhcp_ip_list: "{{ dhcp_logs.stdout_lines | map('regex_search','address=([0-9.]+)') | select('string') | list }}"

    - name: Remove duplicates
      set_fact:
        dhcp_ip_list_unique: "{{ dhcp_ip_list | unique }}"

    - name: Get device IP addresses via nmcli
      shell: nmcli -g DEVICE,IP4.ADDRESS device show | grep -v '^$'
      register: nmcli_output
      changed_when: false

    - name: Parse nmcli IP addresses
      set_fact:
        nmcli_ip_list: "{{ nmcli_output.stdout_lines | map('regex_search','([0-9.]+)') | select('string') | list }}"

    - name: Show simplified DHCP IPs from logs
      debug:
        msg:
          - "DHCP leases found in logs:"
          - "{{ dhcp_ip_list_unique }}"

    - name: Show current device IPs
      debug:
        msg:
          - "Current IPs from nmcli:"
          - "{{ nmcli_ip_list }}"
