---
- name: Detect whether client machine is using DHCP
  hosts: linux_servers
  become: yes
  gather_facts: no

  tasks:

    - name: Detect active network interface
      shell: ip route | awk '/default/ {print $5}'
      register: iface
      changed_when: false

    - name: Detect dynamic IP flag from kernel
      shell: ip addr show {{ iface.stdout }} | grep -qw dynamic
      register: ip_dynamic
      ignore_errors: yes
      changed_when: false

    - name: Detect DHCP lease directory (dhclient)
      stat:
        path: /var/lib/dhcp
      register: dhclient_dir

    - name: Detect DHCP info via nmcli (safe field only)
      shell: nmcli -g DHCP4.OPTION device show {{ iface.stdout }} | wc -l
      register: nm_dhcp_options
      ignore_errors: yes
      changed_when: false

    - name: Final DHCP Detection Result
      debug:
        msg: |
          CLIENT DHCP DETECTION RESULT
          ----------------------------
          Interface        : {{ iface.stdout }}

          Kernel IP state:
            Dynamic IP flag: {{ ip_dynamic.rc == 0 }}

          DHCP Client Files:
            dhclient dir   : {{ dhclient_dir.stat.exists }}

          NetworkManager:
            DHCP options   : {{ nm_dhcp_options.stdout | default('0') }}

          FINAL VERDICT:
          {% if ip_dynamic.rc == 0 or (nm_dhcp_options.stdout | int > 0) %}
          ✅ THIS CLIENT IS UNDER DHCP (Dynamic IP)
          {% else %}
          ❌ THIS CLIENT IS USING STATIC IP
          {% endif %}
