---
- name: Configure OpenSSH Default Shell
  hosts: DTHNPH1FU010052
  gather_facts: no

  tasks:

    - name: Configure DefaultShell using PowerShell
      ansible.builtin.raw: >-
        powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command
        "New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name 'DefaultShell'
        -Value 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
        -PropertyType String -Force"

    - name: Restart SSHD using PowerShell
      ansible.builtin.raw: >-
        powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command
        "Restart-Service sshd"

    - name: Verify DefaultShell using PowerShell
      ansible.builtin.raw: >-
        powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command
        "(Get-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name 'DefaultShell').DefaultShell"
      register: openssh_shell

    - name: Display configured shell
      ansible.builtin.debug:
        msg: "{{ openssh_shell.stdout }}"
